FROM node:12.16.1-alpine

RUN apk update \ 
    && apk --no-cache add  python \ 
    && apk --no-cache add  make \
    && apk --no-cache add  g++ \
    && apk --no-cache add ca-certificates \
    && apk add --update tzdata \
    && cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime \
    && apk del tzdata

RUN mkdir /apps

WORKDIR /apps

ADD ./package.json /apps/
RUN npm install --only=production

ADD ./ /apps

ENV NODE_ENV production
