FROM nginx:1.17.6-alpine
RUN apk add --update tzdata && \
    cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && \
    apk del tzdata
RUN rm /etc/nginx/conf.d/default.conf
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./client/build /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]


